### ISSUE TITLE
Search Places result zero results due to wrong naming

### ISSUE THREAD

**Issue by yumikohey** [eastbayjake/google-locations#21]
// In the usage example, it says using 'keyword', yet it should be 'name';
according to Client side example.
https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=37.42291810,-122.08542120&radius=500&types=food&name=cruise&key=YOUR_API_KEY

locations.search({keyword: 'Google', location: [37.42291810, -122.08542120]}, function(err, response) {
  console.log("search: ", response.results);
 
  locations.details({placeid: response.results[0].place_id}, function(err, response) {
    console.log("search details: ", response.result.website);
    // search details:  http://www.vermonster.com/ 
  });
});

I used 'keyword', No result will come back.

**Comment by eastbayjake** [comment]
Hi @yumikohey,

Thanks for pointing out this issue. The reason the URL you provided is returning ZERO_RESULTS is because there is no restaurant (types=food) with 'cruise' in its name within 500 meters of 37.42291810,-122.08542120. Which business were you trying to match? Here's a working example using `keyword` for the Burger King in Mountain View:

`https://maps.googleapis.com/maps/api/place/nearbysearch/json?location=37.379179,-122.071275&radius=10&types=food&keyword=burger&20king&key=YOUR_API_KEY`

The issue with the module is that the docs suggest using `keyword` but the module defaults `name` to "A" unless a `name` parameter is passed to override it. In looking at this again, I think there should be no default name since `name` is not a required field. The user can then use either `keyword` or `name` based on their own needs for broader results (keyword) or more targeted results (name). I'll submit a PR to change that.
